BEGIN;

-- Table: project
INSERT INTO "project" ("name", "description", "image", "url", "created_at", "updated_at") VALUES
('swift-pledge.com', 'Quasi iusto tempora aliquid consequatur consequuntur assumenda inventore.', 'http://placeimg.com/640/480', 'http://physical-observatory.info', NOW(), NOW()),
('unhappy-accusation.net', 'Eos ullam perferendis in amet.', 'http://placeimg.com/640/480', 'http://strict-freelance.com', NOW(), NOW()),
('any-toe.name', 'Vel in dolorem a et.', 'http://placeimg.com/640/480', 'https://wilted-liquor.com', NOW(), NOW()),
('lopsided-tow-truck.org', 'Dolorem et dolorem consequuntur repudiandae nam necessitatibus mollitia.', 'http://placeimg.com/640/480', 'https://informal-vendor.org', NOW(), NOW()),
('wild-cummerbund.com', NULL, 'http://placeimg.com/640/480', 'https://hoarse-chop.info', NOW(), NOW()),
('fearless-bail.biz', NULL, 'http://placeimg.com/640/480', 'http://aware-caboose.info', NOW(), NOW()),
('defenseless-assault.net', 'Quaerat et deleniti tempore nostrum.', 'http://placeimg.com/640/480', 'http://chilly-metal.net', NOW(), NOW()),
('grotesque-naming.net', 'Ex voluptas voluptatem autem.', 'http://placeimg.com/640/480', 'https://well-off-lox.info', NOW(), NOW()),
('short-forearm.net', 'Dolorem temporibus ea libero odio dolor quae et nihil.', 'http://placeimg.com/640/480', 'http://spanish-verb.info', NOW(), NOW()),
('wasteful-violence.info', 'Nulla aut perspiciatis maxime consequuntur ex neque magnam.', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('fluffy-prostanoid.com', 'Officiis alias officia maiores rem vel dolorum illo.', 'http://placeimg.com/640/480', 'https://sinful-mantle.com', NOW(), NOW()),
('reckless-chance.name', 'Adipisci inventore esse.', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('dual-interviewer.info', 'Impedit facere voluptatem cumque tempora ducimus et.', 'http://placeimg.com/640/480', 'https://capital-unblinking.net', NOW(), NOW()),
('mean-killer.net', 'Assumenda voluptas accusamus repellendus cupiditate.', 'http://placeimg.com/640/480', 'http://glorious-ficlet.net', NOW(), NOW()),
('hairy-calf.info', 'Quisquam omnis autem rerum aut praesentium commodi voluptates.', NULL, NULL, NOW(), NOW()),
('emotional-snowman.org', NULL, 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('neat-baby.name', 'Fugiat voluptatem sunt ipsum ut.', NULL, 'http://suburban-left.info', NOW(), NOW()),
('active-critic.com', NULL, NULL, 'https://wobbly-lunchroom.info', NOW(), NOW()),
('well-informed-dagger.info', 'Distinctio eos ipsam deserunt incidunt labore eveniet et.', 'http://placeimg.com/640/480', 'http://blank-finance.org', NOW(), NOW()),
('spry-guitarist.com', NULL, 'http://placeimg.com/640/480', 'http://windy-mandarin.net', NOW(), NOW()),
('untimely-flight.info', 'Deleniti dignissimos exercitationem suscipit aut distinctio.', NULL, 'https://inconsequential-fight.org', NOW(), NOW()),
('wooden-bitten.info', 'Vitae quis soluta quibusdam.', 'http://placeimg.com/640/480', 'https://silly-completion.net', NOW(), NOW()),
('muted-subsidy.name', NULL, 'http://placeimg.com/640/480', 'http://hidden-sand.name', NOW(), NOW()),
('whopping-dynamo.biz', 'Aut et voluptas minus velit molestiae consequatur repellendus molestiae.', 'http://placeimg.com/640/480', 'http://secondary-chili.biz', NOW(), NOW()),
('potable-rabbit.net', 'Beatae aut fugiat.', 'http://placeimg.com/640/480', 'https://harsh-boot.info', NOW(), NOW()),
('biodegradable-fleck.com', 'Qui ratione quibusdam aut rem minus dolor debitis iusto et.', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('blind-sledge.biz', 'Dolorem recusandae nisi libero ut.', 'http://placeimg.com/640/480', 'https://plastic-flanker.name', NOW(), NOW()),
('fuzzy-cuticle.biz', 'Sunt mollitia porro in.', NULL, 'http://studious-pattern.info', NOW(), NOW()),
('hollow-event.name', 'Est eligendi molestiae cupiditate qui dignissimos facere consequatur reprehenderit consequatur.', 'http://placeimg.com/640/480', 'https://fearful-trigger.info', NOW(), NOW()),
('upright-skullcap.info', 'Et non laudantium explicabo officia quo quam.', 'http://placeimg.com/640/480', 'https://cumbersome-horseradish.info', NOW(), NOW()),
('shimmering-tortoise.com', 'Harum provident dolorum.', 'http://placeimg.com/640/480', 'http://failing-rod.name', NOW(), NOW()),
('chubby-bead.name', 'Sit quia blanditiis impedit quo neque itaque.', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('key-flare.com', 'Delectus et maiores praesentium ullam voluptates amet.', 'http://placeimg.com/640/480', 'http://husky-flung.name', NOW(), NOW()),
('exciting-taxpayer.org', 'Expedita dolores unde harum expedita cumque velit qui dolorum esse.', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('obese-trip.org', NULL, NULL, 'http://honored-department.org', NOW(), NOW()),
('slim-onion.biz', 'In reprehenderit minus blanditiis rem vitae iste.', 'http://placeimg.com/640/480', 'http://adventurous-network.com', NOW(), NOW()),
('all-photography.org', 'At omnis culpa enim.', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('dismal-cigarette.info', 'Iste veritatis ipsa fugiat dolores.', 'http://placeimg.com/640/480', 'https://nutty-mrna.info', NOW(), NOW()),
('sniveling-breastplate.info', 'Consequuntur soluta maxime delectus et corporis dolorum sequi.', 'http://placeimg.com/640/480', 'https://sticky-tintype.com', NOW(), NOW()),
('smooth-tosser.net', 'Accusamus esse quidem placeat sit assumenda perferendis voluptatem praesentium.', 'http://placeimg.com/640/480', 'https://witty-extreme.net', NOW(), NOW());

-- Table: tag
INSERT INTO "tag" ("name", "icon", "color", "created_at", "updated_at") VALUES
('voluptatibus', 'http://placeimg.com/640/480', '#047708', NOW(), NOW()),
('consequatur', NULL, '#5c5865', NOW(), NOW()),
('nam', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('veritatis', 'http://placeimg.com/640/480', '#242044', NOW(), NOW()),
('dolorem', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('ratione', 'http://placeimg.com/640/480', '#47555b', NOW(), NOW()),
('earum', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('sint', 'http://placeimg.com/640/480', NULL, NOW(), NOW()),
('vitae', 'http://placeimg.com/640/480', '#345217', NOW(), NOW()),
('asperiores', 'http://placeimg.com/640/480', '#3a1941', NOW(), NOW()),
('sint', 'http://placeimg.com/640/480', '#406865', NOW(), NOW()),
('eum', 'http://placeimg.com/640/480', '#697125', NOW(), NOW());

-- Table: project_has_tag
INSERT INTO "project_has_tag" ("tag_id", "project_id", "created_at", "updated_at") VALUES
(8, 19, NOW(), NOW()),
(11, 21, NOW(), NOW()),
(6, 40, NOW(), NOW()),
(3, 13, NOW(), NOW()),
(7, 4, NOW(), NOW()),
(7, 31, NOW(), NOW()),
(12, 33, NOW(), NOW()),
(3, 35, NOW(), NOW()),
(5, 8, NOW(), NOW()),
(6, 22, NOW(), NOW()),
(6, 20, NOW(), NOW()),
(12, 12, NOW(), NOW()),
(10, 32, NOW(), NOW()),
(8, 24, NOW(), NOW()),
(3, 12, NOW(), NOW()),
(6, 30, NOW(), NOW()),
(2, 39, NOW(), NOW()),
(6, 16, NOW(), NOW()),
(8, 10, NOW(), NOW()),
(12, 39, NOW(), NOW()),
(2, 34, NOW(), NOW()),
(12, 6, NOW(), NOW()),
(7, 32, NOW(), NOW()),
(2, 17, NOW(), NOW()),
(7, 9, NOW(), NOW()),
(9, 12, NOW(), NOW()),
(9, 39, NOW(), NOW()),
(2, 13, NOW(), NOW()),
(12, 8, NOW(), NOW()),
(4, 30, NOW(), NOW()),
(9, 28, NOW(), NOW()),
(9, 10, NOW(), NOW()),
(9, 19, NOW(), NOW()),
(8, 13, NOW(), NOW()),
(5, 30, NOW(), NOW()),
(10, 15, NOW(), NOW()),
(3, 9, NOW(), NOW()),
(12, 32, NOW(), NOW()),
(5, 36, NOW(), NOW()),
(11, 22, NOW(), NOW()),
(1, 6, NOW(), NOW()),
(3, 30, NOW(), NOW()),
(5, 11, NOW(), NOW()),
(6, 6, NOW(), NOW()),
(4, 29, NOW(), NOW()),
(5, 7, NOW(), NOW()),
(12, 38, NOW(), NOW()),
(4, 26, NOW(), NOW()),
(11, 26, NOW(), NOW()),
(10, 35, NOW(), NOW()),
(7, 1, NOW(), NOW()),
(12, 27, NOW(), NOW()),
(11, 7, NOW(), NOW()),
(2, 22, NOW(), NOW()),
(11, 8, NOW(), NOW()),
(3, 1, NOW(), NOW()),
(5, 5, NOW(), NOW()),
(1, 13, NOW(), NOW()),
(6, 10, NOW(), NOW()),
(10, 29, NOW(), NOW()),
(6, 36, NOW(), NOW()),
(2, 31, NOW(), NOW());

COMMIT;